/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package learn_graphql

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val app = GraphqlApp()

        val graphQL = app.graphQL
        assertNotNull(graphQL.execute("""{bookById(id:"book-1"){name}}""").getData<Any>().also {
            println(it)
        },"query should work")
        assertNotNull(graphQL.execute("{banana}").getData<Any>().also { println(it) },
                "i like bananas")
    }
}
