/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package learn_graphql

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {

        assertNotNull(null, "app should have a greeting")
    }
}
