type Query {
    bookById(id: ID): Book
    hello: String
    banana: String
}
type Book {
    id: ID
    name: String
    pageCount: Int
    author: Author
    user: String
}
type Author {
    id: ID
    firstName: String
    lastName: String
}